name: "Auto Bump Version + Create Tag"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config user.name 'Nazmuz Pranto'
          git config user.email 'npranto4@gmail.com'

      - name: "Bump version | Major"
        if: contains(github.event.pull_request.title, '[MAJOR]')
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          version-type: "major"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bump version | Minor"
        if: contains(github.event.pull_request.title, '[MINOR]')
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          version-type: "minor"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bump version | Patch"
        if: contains(github.event.pull_request.title, '[MINOR]') == false && contains(github.event.pull_request.title, '[MAJOR]') == false
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          version-type: "patch"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
