name: Deploy Tag to Production

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag?"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout tag on prod branch
        run: |
          TAG_NAME=${{ inputs.tag_name }}
          RELEASE_BRANCH=prod
          git checkout main
          git pull origin main
          git checkout $RELEASE_BRANCH
          git reset --hard $TAG_NAME
          git push --force origin $RELEASE_BRANCH

      - name: Log tag pushed to prod
        run: |
          RELEASE_BRANCH=prod
          echo "Tag ($TAG_NAME) has been deployed to production!"
